"""SQLAlchemy engine/session setup.

SQLite is used per the assignment spec. Locally the DB file lives at
backend/app.db (gitignored, regenerated by seed.py). In production, the
container filesystem is ephemeral, so the deploy sets DB_PATH to a file on a
mounted persistent volume (e.g. Railway) — set DB_PATH to override, otherwise
it defaults to the local dev path. `check_same_thread=False` is needed
because FastAPI can hand a request to a different thread than the one that
opened the connection; each request still gets its own Session via
`get_db()`, so this is safe for our single-process dev/demo deployment.
"""
import os
from pathlib import Path

from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

DB_PATH = Path(os.environ.get("DB_PATH", Path(__file__).resolve().parent.parent / "app.db"))
SQLALCHEMY_DATABASE_URL = f"sqlite:///{DB_PATH}"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL, connect_args={"check_same_thread": False}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()
